Update endpoints_sdwan.yaml and sdwan.json File Format Changes
netascode/nac-collector pull request #63
Opened 2024-10-28 10:53 UTC by mekarajesh

2024-10-28 14:16 UTC, tzarski0 commented
This addresses https://github.com/netascode/nac-collector/issues/60 and https://github.com/netascode/nac-collector/issues/61. Output for UX2.0 looks now as expected. @kuba-mazurkiewicz, could you please review and merge?

2024-10-28 14:30 UTC, kuba-mazurkiewicz commented on nac_collector/github_repo_wrapper.py
> -                    # Exclude *_update_rank used in ISE from inspecting
this if statement is for ISE resources which should be excluded, and this line should stay there, otherwise its gonna fail for ISE

2024-10-28 14:30 UTC, kuba-mazurkiewicz requested changes
comment inline

2024-10-29 09:36 UTC, kuba-mazurkiewicz commented
install pre-commit hook and fix linting as per tests.

2024-10-29 10:00 UTC, mekarajesh commented
> comment inline

2024-10-29 10:01 UTC, mekarajesh commented
> install pre-commit hook and fix linting as per tests.

Fixed it kuba, removed unused variable.

2024-10-29 10:41 UTC, kuba-mazurkiewicz commented on nac_collector/github_repo_wrapper.py
> -                    # Exclude *_update_rank used in ISE from inspecting
I would suggest to keep that comment for future reference

2024-10-29 10:42 UTC, kuba-mazurkiewicz requested changes
I would suggest to keep that comment for future reference

2024-10-29 12:23 UTC, merged