Dnac
netascode/nac-collector pull request #69
Opened 2024-11-27 08:23 UTC by kuba-mazurkiewicz

added catalystcenter support (first commit) only supports subset of endpoints

2025-01-07 10:44 UTC, danischm requested changes

2025-01-07 10:44 UTC, danischm commented on endpoints_ise.yaml
I think this file should be removed as it already exists under the `/examples` folder.

2025-01-07 10:44 UTC, danischm commented on nac_collector/cisco_client_catalystcenter.py
> +        elif data.get("SearchResult"):
Is this required or just carried over from ISE?

2025-01-07 10:44 UTC, danischm commented on nac_collector/cisco_client_catalystcenter.py
> +    def process_ers_api_results(self, data):
Is this required?

2025-01-07 10:44 UTC, danischm commented on nac_collector/cisco_client_catalystcenter.py
> +                id_value = i["rule"]["id"]
Do we need this for CC?

2025-01-16 13:48 UTC, kuba-mazurkiewicz commented on endpoints_ise.yaml
done

2025-01-16 13:49 UTC, kuba-mazurkiewicz commented on nac_collector/cisco_client_catalystcenter.py
> +                id_value = i["rule"]["id"]
we don't that was carried over from ise, it can be removed, cause cc doesnt have rule in json body in any of the object

2025-01-16 13:57 UTC, kuba-mazurkiewicz commented on nac_collector/cisco_client_catalystcenter.py
> +    def process_ers_api_results(self, data):
its not, removed

2025-01-16 13:57 UTC, kuba-mazurkiewicz commented on nac_collector/cisco_client_catalystcenter.py
> +        elif data.get("SearchResult"):
carried over from ise, removed

2025-02-03 10:49 UTC, merged